# Generated by Django 3.2 on 2021-05-07 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conf_app', '0003_alter_calendarevent_participants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendarevent',
            name='participants',
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='participants',
            field=models.CharField(default='email', max_length=1024),
            preserve_default=False,
        ),
    ]
